### PR TITLE
Merging Frendshipv2 to development

### PR DESCRIPTION
**Pull request by Kyle-Law**
Thanks for reviewing and below are some features of my app

- Live Link is deployed to heroku and can be accessed via https://social-media-kyle.herokuapp.com/
- To add friend, go to All user page, > click add friend > 'pending request' will be shown > go to the user page by click the user name > click accept > back to user page > 'Already Friend' will be shown > If rejected is selected, the request will be destroy and 'Add Friend' is possible again.
- Rubocop has been setup but doesn't show in PR. When I run 'rubocop .','31 files inspected, no offenses detected' detected is shown.
- To test, run 'rspec' ,'26 examples, 0 failures' will be shown.
- The javascript light/dark mode toggle functionality works well locally but not on heroku, feel free to shed some light on that matter.

:)

### CODE REVIEW

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
## Hi @Kyle-Law .
### Very good job so far.

However, there are some issues that need to be addressed before move on to the next milestone.  👨‍💻  ⬇️ 

****
- [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby).

This is what we have at this moment:

Screen Shot 2020-08-13 at 8 44 42 PM

We can improve this in implementing:

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
Now we can get the required data through our association in the method that includes the query:

Screen Shot 2020-08-13 at 8 53 08 PM

You may also want to use this association in your method that retrieves the user and friends' posts.

Screen Shot 2020-08-13 at 9 00 22 PM


****

### **Please make the changes required and submit for re-review once you are ready!** 

****

### Status: Changes required. ♻️  
****

Happy coding!  💻  
Have a great day 🙂

If you need more clarifications kindly reach me on slack.
**[TSE:  David Elí]** 
Slack: @ David Eli Martinez Garcia

**Comment by Kyle-Law** [comment]
Thanks @davitomix for your insightful review and the inverse friendships have been updated.

- Live Link is deployed to heroku and can be accessed via https://social-media-kyle.herokuapp.com/
- Rubocop has been setup but doesn't show in PR. When I run 'rubocop .','31 files inspected, no offenses detected' detected is shown.
- To add friend, go to All user page, > click add friend > 'pending request' will be shown > go to the user page by click the user name > click accept > back to user page > 'Already Friend' will be shown > - If rejected is selected, the request will be destroy and 'Add Friend' is possible again.
Rubocop has been setup but doesn't show in PR. When I run 'rubocop .','31 files inspected, no offenses detected' detected is shown.
- To test, run 'rspec' ,'26 examples, 0 failures' will be shown.
- The javascript light/dark mode toggle has been refined. Now it sustains throughout the app without errors.

:)

**Review by wathigo — CHANGES_REQUESTED** [review]
### Changes Required
Great work implementing some of the suggested changes.

**REQUIRED**
* The application on an attempt to sign out. See this :point_down: 
Screenshot from 2020-08-19 10-29-57
* The GitHub actions are not working may be due to the fact that we have both stickler and GitHub actions configurations. Let's remove the `stickler.yml` file since it's not part of GitHub actions configuration files as shown [here](https://github.com/microverseinc/linters-config/tree/master/ror).

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

**Comment by Kyle-Law** [comment]
Good day! Thanks @wathigo for your insightful review and the signout path have been fixed by adding back rails_ujs which was previously deleted.
Besides, I've deleted the stickler.yml file as you mentioned and also rewind my steps for setting up linters, however, it doesn't appear on PR.

Nonetheless, the CLI checking works, you should see no errors upon running `rubocop` and `npx stylelint "**/*.{css,scss}"`.

:)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Kyle-Law, great job with this project :+1: However, we need to fix the GitHub actions, we cannot approve the project without fixing it. If you need help in contacting a TSE to help you fix it, kindly check this [article](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-#)

[OPTIONAL]
- To setup a more professional repo, kindly add instructions about `how to clone the project`, `how to run test`. For example; `git clone <repo>`, `bundle install`, `rails db:create`, `rails db:migrate` etc

Kindly fix this and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Kyle-Law** [comment]
Thanks @addod19 for setting a high bar, the issue is resolved by delete and re-create the linters.yml file. Besides, your recommendation for setting up a professional GitHub repo is implemented.

:)

**Review by mosesogwo — APPROVED** [review]
**Hello! :wave: Great job! :+1: Your milestone is approved**

Please take note that circle_posts could be retrieved using a simpler and more efficient method like this:
```ruby

def circle_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end

```

_**Cheers:stars:**_

### Status: Approved :heavy_check_mark:

**Pull request merged**
